#!/bin/bash
distro=$(cat /etc/os-release | head -1 | sed 's/"//g' | cut -d= -f2)
host=$(cat /sys/devices/virtual/dmi/id/product_name /sys/devices/virtual/dmi/id/product_version | tr '\n' ' ')
kernel=$(uname -r)
shell=$(echo `$SHELL --version` | cut -d'(' -f1)
uptime=$(uptime -p)
memory=$(free -hm | awk 'NR==2{printf "%s/%s\n", $3,$2}')

if [[ $distro == *"Debian"* || *"Ubuntu"* ]]
then
  packages=$(dpkg-query -W | wc -l)
fi

if [[ $distro == *"Slackware"* ]]
then
  packages=$(ls /var/log/packages | wc -l)
fi

if [ -n "$XDG_CURRENT_DESKTOP" ]
then
  de=$(echo "$XDG_CURRENT_DESKTOP")
else
  de=$(echo "None")
fi

if [ -n "$GDMSESSION" ]
then
  session=$(echo "$GDMSESSION")
else
  session=$(echo "None")
fi

echo "OS: $distro"
echo "Host: $host"
echo "Kernel: $kernel"
echo "Shell: $shell"
echo "Uptime: $uptime"
echo "Packages: $packages"
echo "DE: $de"
echo "Session: $session"
echo "Memory: $memory"
